language: android
jdk: oraclejdk8

env:
 global:
    - ANDROID_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2

before_install:
  - ./travis_prebuild.sh;

script:
    - ./gradlew build check

android:
  components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

deploy:
  provider: script
  script: ./gradlew -c qatja-android/publish-settings.gradle clean bintrayUpload
  skip_cleanup: true
  on:
    tags: true